[package]
name = "jni-macro"
version = "0.1.0"
edition = "2024"

[dependencies]
jni-macro-core = { path = "../jni-core" }
jni-macro-derive = { path = "../jni-derive" }

# Re-export dependencies that users will need
inventory = "0.3"
